Add Week 5 slides - functions, documentation, namespace part 1
r4ds/bookclub-rpkgs-old pull request #28
Opened 2020-10-28 20:42 UTC by jonleslie

This will bring the files for my presentation on 2020-10-27.

2020-10-28 20:44 UTC, jonleslie commented
I'm confused as to why Jon Harmon's previous commits are showing up in this pull request. Perhaps it has something to do with how I merged from the upstream to my local main branch? Please tell me if I've done something dumb and I I'll try to fix it.

2020-10-29 13:46 UTC, tanho63 requested changes

2020-10-29 13:46 UTC, tanho63 commented on Presentations/Week05/Cohort1/functions_docs_namespace.Rmd
> +---
For consistency's sake, can you rename this folder from Cohort1 to Cohort01?

2020-10-29 14:00 UTC, jonthegeek commented
I set this up to merge into a dev branch. If we squash and merge, we can kill the weird merge history here, and then ~easily merge into main. I think.

2020-10-29 14:03 UTC, merged

2020-10-29 14:04 UTC, tanho63 commented
OK I think I did the thing.